name = "msra-uk"

compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]

main = ".worker-next/index.mjs"
assets = { directory = ".worker-next/assets", binding = "ASSETS" }

[[kv_namespaces]]
binding = "NEXT_CACHE_WORKERS_KV"
id = "6d9d171172d441c8ba0431ace74ff00f"